export const LOGIN = 'LOGIN';
export const SIGN_UP = 'SIGN_UP';
export const LOGIN_WITH_SIGN_UP = 'LOGIN_WITH_SIGN_UP';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_VERIFY = 'FORGOT_PASSWORD_VERIFY';
export const FORGOT_PASSWORD_UPDATE = 'FORGOT_PASSWORD_UPDATE';
