export const GET_PUBLIC_PROFILE = 'GET_PUBLIC_PROFILE';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_COMPETITIVE_PROGRAMMING = 'GET_COMPETITIVE_PROGRAMMING';
export const GET_TECH_USED = 'GET_TECH_USED';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_TECH = 'ADD_TECH';

export const UPDATE_PUBLIC_PROFILE = 'UPDATE_PUBLIC_PROFILE';
export const UPDATE_COMPETITIVE_PROGRAMMING = 'UPDATE_COMPETITIVE_PROGRAMMING';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_TECH = 'DELETE_TECH';
