export const CACHE_ALL_USERS = 'CACHE_ALL_USERS';

export const GET_SEARCH_ACCESS_TOKEN = 'GET_SEARCH_ACCESS_TOKEN'

export const SEARCHED_USER_GET_PUBLIC_PROFILE = 'SEARCHED_USER_GET_PUBLIC_PROFILE';
export const SEARCHED_USER_GET_PROJECTS = 'SEARCHED_USER_GET_PROJECTS';
export const SEARCHED_USER_GET_COMPETITIVE_PROGRAMMING = 'SEARCHED_USER_GET_COMPETITIVE_PROGRAMMING';
export const SEARCHED_USER_GET_TECH_USED = 'SEARCHED_USER_GET_TECH_USED';
